#!/usr/bin/env bash
# 1. Reads a version number from ./marlin_version.
# 2. Clones Marlin at that tag into ./.Marlin.
# 3. Symlinks ./Configuration.h and Configuration_adv.h.
# 4. Opens VsCode in the ./.Marlin directory.

if [ ! -f ./marlin_version ]; then
	echo "File ./marlin_version not found"
	exit 1
fi

marlin_version=$(cat ./marlin_version)

if [ -z "$marlin_version" ]; then
	echo "File ./marlin_version is empty"
	exit 1
fi

if [ -d ./.Marlin ]; then
	echo "Removing old Marlin version"
	rm -rf "./.Marlin" || { echo "Failed to remove ./.Marlin"; exit 1; }
fi

git clone --branch "$marlin_version" --depth 1 "git@github.com:MarlinFirmware/Marlin.git" "./.Marlin" || { echo "Failed to clone MarlinFirmware/Marlin at $marlin_version"; exit 1; }
echo "Cloned MarlinFirmware/Marlin at $marlin_version"

cp -srf ./Configuration.h ./.Marlin/Marlin/Configuration.h
cp -srf ./Configuration_adv.h ./.Marlin/Marlin/Configuration_adv.h
cp -srf ./_Bootscreen.h ./.Marlin/Marlin/_Bootscreen.h
cp -srf ./_Statusscreen.h ./.Marlin/Marlin/_Statusscreen.h

echo "Symlinked configuration files into Marlin $marlin_version"
code "./.Marlin"
